# Generated by Django 4.2.7 on 2023-12-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('X', '0002_manage_basquetbolista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basquetbolista',
            name='altura',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='basquetbolista',
            name='edad',
            field=models.CharField(max_length=10),
        ),
    ]
