# Generated by Django 3.2.25 on 2024-11-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('X', '0004_auto_20241126_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animales',
            old_name='cliente',
            new_name='persona',
        ),
    ]
