# Generated by Django 3.2.25 on 2024-12-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('X', '0005_rename_cliente_animales_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='telefono_suplente',
            field=models.CharField(default='', max_length=9),
        ),
    ]
